SELECT t.SECU_CODE, t.EXCHANGE, t.SECU_NAME, t.ISIN, t.CURRENCY,
       t.LIST_DATE, t.DELIST_DATE,
       t.TYPE AS SRC_INSTRUMENT_TYPE,
       t.UPDATE_TIME AS UPDATED_AT
FROM JYDB.SECURITY_MASTER t
WHERE (:mode = 'full')
   OR (:mode = 'incremental' AND t.UPDATE_TIME >= TO_TIMESTAMP(:since, 'YYYY-MM-DD HH24:MI:SS'))
  AND t.EXCHANGE IN ('SH','SZ','BJ','HK','CFFEX','SHFE','DCE','CZCE','INE')
  AND t.TYPE IN ('EQUITY','INDEX','FUND','BOND','FUTURES','OPTIONS');
