SELECT w.S_INFO_WINDCODE AS WINDCODE,
       w.S_INFO_NAME, w.S_INFO_ISIN, w.S_INFO_CURRENCY,
       w.S_INFO_LISTDATE, w.S_INFO_DELISTDATE,
       w.S_INFO_TYPE AS SRC_INSTRUMENT_TYPE,
       w.OPDATE AS UPDATED_AT
FROM WIND.SECURITY_MASTER w
WHERE (:mode = 'full')
   OR (:mode = 'incremental' AND w.OPDATE >= TO_TIMESTAMP(:since, 'YYYY-MM-DD HH24:MI:SS'))
  AND w.S_INFO_TYPE IN ('EQUITY','INDEX','FUND','BOND','FUTURES','OPTIONS');
